sudo: required
services:
  - docker

before_install:
  - docker build -t wilsonau/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true wilsonau/react-test npm test

after_success:
  - docker build -t wilsonau/multi-client ./client
  - docker build -t wilsonau/multi-nginx ./nginx
  - docker build -t wilsonau/multi-server ./server
  - docker build -t wilsonau/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --pasword-stdin
  # Take those images and push them to docker hub
